apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-hello-sm
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: flask-hello
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
